script: |
  export SUPER_DB=test
  super db init -q
  super db create -q -orderby a:asc poolA
  super db create -q -orderby b:desc poolB
  super db load -q -use poolA a.sup
  super db load -q -use poolB b.sup
  super db -S -c 'from :pools | drop id | sort name | drop ts'
  echo ===
  super db -fusion -S -c 'from poolA@main:objects | {nameof:nameof(this),...this} | drop id'
  super db -S -c 'from poolA:log | cut nameof(this)'

inputs:
  - name: a.sup
    data: |
      {a:1}
      {a:2}
  - name: b.sup
    data: |
      {b:3}
      {b:2}
      {b:1}

outputs:
  - name: stdout
    data: |
      type "order.Which" = string
      type "field.Path" = [string]
      type "order.SortKey" = {
        order: "order.Which",
        path: "field.Path"
      }
      type "order.SortKeys" = ["order.SortKey"]
      {
        name: "poolA",
        layout: [
          {
            order: "asc",
            path: [
              "a"
            ]
          }
        ]::order.SortKeys,
        objectcap: 1048576::uint64,
        framecap: 20000::uint64
      }
      {
        name: "poolB",
        layout: [
          {
            order: "desc",
            path: [
              "b"
            ]
          }
        ]::order.SortKeys,
        objectcap: 1048576::uint64,
        framecap: 20000::uint64
      }
      ===
      {
        nameof: "data.Object",
        min: 1,
        max: 2,
        count: 2::uint64,
        size: 633
      }
      {
        nameof: "db.BranchTip"
      }
      {
        nameof: "Commit"
      }
