package bsup

import (
	"encoding/binary"
	"errors"
	"fmt"
	"io"

	"github.com/superdb/super/sup"
)

// This file defines the section formats of BSUP serialized entities, e.g.,
// files, streams, cloud objects, etc.  The format supports efficient random
// access, streaming access, metadata pushdown/pruning, concatenation of entities,
// and efficient type introspection for type checking and query optimization.
//
// An entity that encodes BSUP data is called a BSUP container, which might be
// stored in a file or a cloud object.  A container is composed of multiple
// independently serialized sections called SuperFrames.  SuperFrames may be
// concatenated together and the BSUP Reader will treat the concatenated
// SuperFrames as a single entity (e.g., providing a summary type across the
// entire BSUP Container).
//
// When writing data into the BSUP format, the Frames are automatically terminated
// based on a configured target size similar to Parquet row groups or Arrow
// record batches.  A SuperFrame is generated when Flush is called on the
// serializer or when the final Close is called.
//
// To support live-streaming use cases, Frames may be pushed out immediately
// by calling FlushFrame before a Frame's worth of data is present.
//
// Frames may be either Row Frames or Column Frames and the reader will
// treat a mixture of such Frames as a contiguous sequence of values.
// Columns are generated by default but Rows may be produce by invoking
// a RowWriter instead of a Serializer.  All of the Frames in a SuperFrame
// must be the same kind (i.e., Row or Column) but Row SuperFrames and
// Column SuperFrames may be intermixed in a BSUP Container.
//
// When input isn't seekable (e.g., stdin or a network connection), then
// the input is read into memory in its entirety, which is then a seekable entity.
// If read streaming is configured, then type introspection is not available
// and the data is not read completely into memory.  Instead, each Frame is
// processed sequentially.
//
// Each Frame includes a header with magic and indicates which type of frame
// it is, e.g., column data, row data, row type data, or column type value data.
// Currently, any type values used in a Columns frame (e.g., for type-value or
// fusion vectors) are encoded idempotently within the Frame; they are loaded on demand.
// This creates some redundancy in the type data as the same type will be recoded
// again in each Frame.
//
// Each Frame header also includes the fusion type of all the data in the Frame,
// encoded as a type value.
//
// Each SuperFrame includes a trailer that encodes the size of the SuperFrame,
// allowing reverse traversal from the end of a seekable entity to find each
// SuperFrame in the BSUP entity.
//
// Note that this design allows Containers to simply be concatenated together,
// which simply produces a larger and still-valid Container.

const (
	Version           = 25
	MaxMetaSize       = 100 * 1024 * 1024
	MaxFrameSize      = 2 * 1024 * 1024 * 1024
	MaxSuperFrameSize = 256 * MaxFrameSize
)

const (
	SuperMagic  = "SUPS"
	ColumnMagic = "SUPC"
	RowMagic    = "SUPR"
)

type Header interface {
	Size() uint64 // Total size of the frame including header
	HeaderSize() uint64
}

// Structure of ColumnFrame
//
// S U P C (4 byte string)
// Version (2 bytes)
// OOB flag (1 byte)
// Root ID (4 bytes)
// Frame size (8 bytes) - entire frame including header to end of data section
// Fused type size (8 bytes) - 0 if not present
// Metadata section size (8 bytes)
// [variable data]
// Metadata (encoded as a rows SuperFrame)
// Typedefs (encoded as bytes of typedefs serialization)
// Fused type value (encoded as raw type value bytes)
// Data section (encoded as raw bytes with size = FrameSize - MetadataSize)
type ColumnHeader struct {
	Version       uint16 // off 4
	OOB           bool   // 6
	Root          uint32 // 7
	FrameSize     uint64 // 11
	MetadataSize  uint64 // 19
	TypedefsSize  uint64 // 27
	FusedTypeSize uint64 // 35
}

const ColumnHeaderSize = 43

func newColumnHeader(oob bool, root ID, metadataSize, typedefsSize, fusedTypeSize, dataSectionSize uint64) ColumnHeader {
	frameSize := ColumnHeaderSize + metadataSize + typedefsSize + fusedTypeSize + dataSectionSize
	return ColumnHeader{
		Version:       Version,
		OOB:           oob,
		Root:          uint32(root),
		FrameSize:     frameSize,
		MetadataSize:  metadataSize,
		TypedefsSize:  typedefsSize,
		FusedTypeSize: fusedTypeSize,
	}
}

func (c *ColumnHeader) Size() uint64 {
	return c.FrameSize
}

func (*ColumnHeader) HeaderSize() uint64 {
	return ColumnHeaderSize
}

func (c ColumnHeader) Serialize() []byte {
	var bytes [ColumnHeaderSize]byte
	copy(bytes[0:4], []byte(ColumnMagic))
	binary.LittleEndian.PutUint16(bytes[4:], c.Version)
	if c.OOB {
		bytes[6] = 1
	}
	binary.LittleEndian.PutUint32(bytes[7:], c.Root)
	binary.LittleEndian.PutUint64(bytes[11:], c.FrameSize)
	binary.LittleEndian.PutUint64(bytes[19:], c.MetadataSize)
	binary.LittleEndian.PutUint64(bytes[27:], c.TypedefsSize)
	binary.LittleEndian.PutUint64(bytes[35:], c.FusedTypeSize)
	return bytes[:]
}

func (c *ColumnHeader) Deserialize(bytes [ColumnHeaderSize]byte) {
	c.Version = binary.LittleEndian.Uint16(bytes[4:])
	if bytes[6] == 0 {
		c.OOB = false
	} else {
		c.OOB = true
	}
	c.Root = binary.LittleEndian.Uint32(bytes[7:])
	c.FrameSize = binary.LittleEndian.Uint64(bytes[11:])
	c.MetadataSize = binary.LittleEndian.Uint64(bytes[19:])
	c.TypedefsSize = binary.LittleEndian.Uint64(bytes[27:])
	c.FusedTypeSize = binary.LittleEndian.Uint64(bytes[35:])
}

func (c ColumnHeader) MetadataSection() (int64, int64) {
	return ColumnHeaderSize, int64(c.MetadataSize)
}

func (c ColumnHeader) TypedefsSection() (int64, int64) {
	return ColumnHeaderSize + int64(c.MetadataSize), int64(c.TypedefsSize)
}

func (c ColumnHeader) FusedTypeSection() (int64, int64) {
	return ColumnHeaderSize + int64(c.MetadataSize) + int64(c.TypedefsSize), int64(c.FusedTypeSize)
}

func (c ColumnHeader) SegmentsSection() (int64, int64) {
	off := ColumnHeaderSize + int64(c.MetadataSize) + int64(c.TypedefsSize) + int64(c.FusedTypeSize)
	return off, int64(c.FrameSize) - off
}

func (c ColumnHeader) check() error {
	if err := checkVersion(c.Version); err != nil {
		return err
	}
	if err := checkSize("column frame", int(c.FrameSize), MaxMetaSize); err != nil {
		return err
	}
	if err := checkSize("fused type", int(c.FusedTypeSize), MaxMetaSize); err != nil {
		return err
	}
	if err := checkSize("metadata section", int(c.MetadataSize), MaxMetaSize); err != nil {
		return err
	}
	return checkSize("typedefs section", int(c.TypedefsSize), MaxMetaSize)
}

// Structure of RowFrame
//
// S U P R (4 byte string)
// Version (2 bytes)
// Frame size (8 bytes) - entire frame including header to end of data section
// Fused type size (8 bytes) - 0 if not present
// Typedefs section size (8 bytes)
// OOB flag (1 byte)
// Fused type value (variable bytes)
// Typedefs section (variable bytes)
// Values section size = FrameSize - (FusedTypeSize+TypedefsSize)
type RowHeader struct {
	Version       uint16
	FrameSize     uint64
	FusedTypeSize uint64
	TypedefsSize  uint64
	OOB           bool
}

const RowHeaderSize = 31

func newRowHeader(oob bool, typedefsSize, fusedTypeSize, dataSectionSize uint64) RowHeader {
	frameSize := RowHeaderSize + +typedefsSize + fusedTypeSize + dataSectionSize
	return RowHeader{
		Version:       Version,
		OOB:           oob,
		FrameSize:     frameSize,
		TypedefsSize:  typedefsSize,
		FusedTypeSize: fusedTypeSize,
	}
}

func (r *RowHeader) Size() uint64 {
	return r.FrameSize
}

func (*RowHeader) HeaderSize() uint64 {
	return RowHeaderSize
}

func (r RowHeader) Serialize() []byte {
	var bytes [RowHeaderSize]byte
	copy(bytes[0:4], []byte(RowMagic))
	binary.LittleEndian.PutUint16(bytes[4:], r.Version)
	binary.LittleEndian.PutUint64(bytes[6:], r.FrameSize)
	binary.LittleEndian.PutUint64(bytes[14:], r.FusedTypeSize)
	binary.LittleEndian.PutUint64(bytes[22:], r.TypedefsSize)
	if r.OOB {
		bytes[30] = 1
	}
	return bytes[:]
}

func (r *RowHeader) Deserialize(bytes [RowHeaderSize]byte) {
	r.Version = binary.LittleEndian.Uint16(bytes[4:])
	r.FrameSize = binary.LittleEndian.Uint64(bytes[6:])
	r.FusedTypeSize = binary.LittleEndian.Uint64(bytes[14:])
	r.TypedefsSize = binary.LittleEndian.Uint64(bytes[22:])
	if bytes[30] == 0 {
		r.OOB = false
	} else {
		r.OOB = true
	}
}

func (c RowHeader) FusedTypeSection() (int64, int64) {
	return RowHeaderSize, int64(c.FusedTypeSize)
}

func (c RowHeader) TypedefsSection() (int64, int64) {
	return RowHeaderSize + int64(c.FusedTypeSize), int64(c.TypedefsSize)
}

func (c RowHeader) DataSection() (int64, int64) {
	off := RowHeaderSize + int64(c.FusedTypeSize) + int64(c.TypedefsSize)
	return off, int64(c.FrameSize) - off
}
func (r RowHeader) check() error {
	if err := checkVersion(r.Version); err != nil {
		return err
	}
	if err := checkSize("row frame", int(r.FrameSize), MaxMetaSize); err != nil {
		return err
	}
	if err := checkSize("fused type", int(r.FusedTypeSize), MaxMetaSize); err != nil {
		return err
	}
	return checkSize("typedefs section", int(r.TypedefsSize), MaxMetaSize)
}

// Structure of SuperFrame footer
//
// S U P S (4 byte string)
// Version (2 bytes)
// Footer size (8 bytes) - total size of footer not counting last 8 bytes
// Total size of previous SuperFrame (8 bytes) - excludes this SuperFrame footer
// Fused type value (variable bytes) - length is FooterSize - SuperFooterSize
// Footer size (8 bytes) - same as above for backward traversal
type SuperFooter struct {
	Version        uint16 // off 4
	FooterSize     uint64 // off 6
	SuperFrameSize uint64 // off 14
}

const (
	SuperFooterSize = 22 // size of header excluding fused type and length trailer
	SuperFooterPad  = 8  // extra space for length trailer
)

func newSuperFooter(superFrameSize, fusedTypeSize uint64) SuperFooter {
	return SuperFooter{
		Version:        Version,
		FooterSize:     fusedTypeSize + SuperFooterSize,
		SuperFrameSize: superFrameSize,
	}
}

func (s *SuperFooter) Size() uint64 {
	return s.FooterSize + SuperFooterPad
}

func (s *SuperFooter) HeaderSize() uint64 {
	return SuperFooterSize
}

func (s *SuperFooter) TypedefsSize() uint64 {
	return s.Size() - s.HeaderSize() - SuperFooterPad
}

// Serialize the front part of a SuperHeader.  The caller is responsible for
// writing the length trailer after the fused type.
func (s SuperFooter) Serialize() []byte {
	var bytes [SuperFooterSize]byte
	copy(bytes[0:4], []byte(SuperMagic))
	binary.LittleEndian.PutUint16(bytes[4:], s.Version)
	binary.LittleEndian.PutUint64(bytes[6:], s.FooterSize)
	binary.LittleEndian.PutUint64(bytes[14:], s.SuperFrameSize)
	return bytes[:]
}

func (s *SuperFooter) Deserialize(bytes [SuperFooterSize]byte) {
	s.Version = binary.LittleEndian.Uint16(bytes[4:])
	s.FooterSize = binary.LittleEndian.Uint64(bytes[6:])
	s.SuperFrameSize = binary.LittleEndian.Uint64(bytes[14:])
}

func (s SuperFooter) check() error {
	if err := checkVersion(s.Version); err != nil {
		return err
	}
	if err := checkSize("super footer", int(s.FooterSize), MaxMetaSize); err != nil {
		return err
	}
	return checkSize("super frame", int(s.SuperFrameSize), MaxSuperFrameSize)
}

func readNextHeader(r io.ReaderAt, off int64) (Header, error) {
	var magic [4]byte
	if err := readHeaderBytes(r, off, magic[:], "magic"); err != nil {
		if err == io.ErrUnexpectedEOF {
			err = nil
		}
		return nil, err
	}
	switch magic := string(magic[:]); magic {
	case SuperMagic:
		var bytes [SuperFooterSize]byte
		if err := readHeaderBytes(r, off, bytes[:], "super footer"); err != nil {
			return nil, err
		}
		var footer SuperFooter
		footer.Deserialize(bytes)
		return &footer, footer.check()
	case ColumnMagic:
		var bytes [ColumnHeaderSize]byte
		if err := readHeaderBytes(r, off, bytes[:], "column header"); err != nil {
			return nil, err
		}
		var header ColumnHeader
		header.Deserialize(bytes)
		return &header, header.check()
	case RowMagic:
		var bytes [RowHeaderSize]byte
		if err := readHeaderBytes(r, off, bytes[:], "row header"); err != nil {
			return nil, err
		}
		var header RowHeader
		header.Deserialize(bytes)
		return &header, header.check()
	default:
		return nil, fmt.Errorf("unknown header magic: %s", sup.QuotedString(magic))
	}
}

func Probe(r io.Reader) error {
	h, err := ReadHeader(r)
	if err != nil {
		return err
	}
	if _, ok := h.(*SuperFooter); ok {
		return errors.New("file cannot begin with a super footer")
	}
	return nil
}

func ReadHeader(r io.Reader) (Header, error) {
	var magic [4]byte
	if _, err := io.ReadFull(r, magic[:]); err != nil {
		if err == io.EOF {
			return nil, nil
		}
		return nil, errors.New("short file")
	}
	switch magic := string(magic[:]); magic {
	case SuperMagic:
		var bytes [SuperFooterSize]byte
		if _, err := io.ReadFull(r, bytes[4:]); err != nil {
			return nil, errors.New("short file")
		}
		var footer SuperFooter
		footer.Deserialize(bytes)
		return &footer, footer.check()
	case ColumnMagic:
		var bytes [ColumnHeaderSize]byte
		if _, err := io.ReadFull(r, bytes[4:]); err != nil {
			return nil, errors.New("short file")
		}
		var header ColumnHeader
		header.Deserialize(bytes)
		return &header, header.check()
	case RowMagic:
		var bytes [RowHeaderSize]byte
		if _, err := io.ReadFull(r, bytes[4:]); err != nil {
			return nil, errors.New("short file")
		}
		var header RowHeader
		header.Deserialize(bytes)
		return &header, header.check()
	default:
		return nil, fmt.Errorf("unknown header magic: %s", sup.QuotedString(magic))
	}
}

func readHeaderBytes(r io.ReaderAt, off int64, buf []byte, which string) error {
	n, err := r.ReadAt(buf, off)
	if err != nil {
		return checkEOF(err)
	}
	if n < len(buf) {
		return fmt.Errorf("short header reading %s: read %d bytes, expected %d", which, n, len(buf))
	}
	return nil
}

func checkEOF(err error) error {
	if err == io.EOF {
		return io.ErrUnexpectedEOF
	}
	return err
}

func checkVersion(version uint16) error {
	if version != Version {
		return fmt.Errorf("version mismatch: expected %d, found %d", Version, version)
	}
	return nil
}

func checkSize(msg string, size, max int) error {
	// We check for underflow of size since they are stored as unsigned.
	if size > max || size < 0 {
		return fmt.Errorf("out-of-range value: %s: found %d, max %d", msg, size, max)
	}
	return nil
}
